### ISSUE TITLE
some files are missing in v2.0.1

### ISSUE THREAD

**Issue by ianhe8x** [atlassian/cz-lerna-changelog#19]
lib/autocomplete-questions.js and lib/make-default-questions.js are missing in the latest release.
When I run git cz, get this error `Cannot find module './make-default-questions'`

**Comment by ianhe8x** [comment]
@lukebatchelor I think the problem is caused by your publish pipeline, because i tried to run npm run build locally and those files are there. If that's the case, I won't be able to contribute a fix.

**Comment by lukebatchelor** [comment]
Should be [fixed in 2.0.2](https://unpkg.com/cz-lerna-changelog@2.0.2/lib/)

Thanks for reporting/digging @ianhe8x

**Comment by lukebatchelor** [comment]
Ha. Decided to dig in, it looks like this was a breaking change in npm.

[The docs](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package) say that any files that are gitignored will be npm ignored if you don't have an `.npmignore` file and to create an empty `.npmignore` file if you want to opt out of that behaviour.

And it looks like that was the case until npm version `5.4.1`.

![image](https://user-images.githubusercontent.com/18694878/50135613-dfaf8100-02e8-11e9-9453-1219dcb959fa.png)


For anyone interested, you can either add the files you wanted to the files array of your `package.json`
or explicitly add them to your `.npmignore` as never ignored

```
+lib  # make sure we never npmignore the lib directory 
```
